controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
fallback_404:
    path: /{any}
    controller: App\Controller\ErrorController::notFound
    requirements:
        any: ".+"
